[tool.poetry]
name = "deeplearning-projects"
version = "0.1.0"
description = ""
authors = ["Rachit Sengupta <rachit_sengupta@intuit.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
